### ISSUE TITLE
妈耶 是kotlin  但是有错

### ISSUE THREAD

**Issue by 643063150** [pye52/Recorder#2]
`  kotlin.UninitializedPropertyAccessException: lateinit property camera has not been initialized
        at com.kanade.recorder.camera1.CameraManager.updateHolder(CameraManager.kt:27)
        at com.kanade.recorder.camera1.Camera1Fragment.surfaceCreated(Camera1Fragment.kt:205)
        at android.view.SurfaceView.updateWindow(SurfaceView.java:593)
        at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:184)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2108)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1138)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6227)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:884)
        at android.view.Choreographer.doCallbacks(Choreographer.java:696)
        at android.view.Choreographer.doFrame(Choreographer.java:631)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:870)
        at android.os.Handler.handleCallback(Handler.java:743)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5546)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)`

**Comment by pye52** [comment]
是最新的吗…这个问题我记得修复了，而且只在部分机型上才会报这个错
暂时不维护了，要做也是推翻重写
如有需求可以看这个：https://github.com/CJT2325/CameraView

**Comment by 643063150** [comment]
en  是的，华为的平板，我看一下 谢谢
